-- 创建天气相关表
-- agri_climate_daily: 每日天气数据
-- agri_weather_forecast: 天气预报
-- agri_weather_alert: 天气预警

CREATE TABLE agri_climate_daily (
    id VARCHAR(64) NOT NULL COMMENT '主键ID',
    user_id VARCHAR(64) NOT NULL COMMENT '所属用户ID',
    farm_id VARCHAR(64) NULL COMMENT '关联农场ID',
    location_id VARCHAR(64) NULL COMMENT '和风天气LocationID',
    province VARCHAR(64) NULL COMMENT '省份',
    city VARCHAR(64) NULL COMMENT '城市',
    district VARCHAR(64) NULL COMMENT '区县',
    longitude DECIMAL(10,7) NULL COMMENT '经度',
    latitude DECIMAL(10,7) NULL COMMENT '纬度',
    record_date DATE NOT NULL COMMENT '记录日期',
    obs_time DATETIME NULL COMMENT '数据观测时间',
    temp INT NULL COMMENT '温度（摄氏度）',
    feels_like INT NULL COMMENT '体感温度',
    weather_icon VARCHAR(16) NULL COMMENT '天气图标代码',
    weather_text VARCHAR(64) NULL COMMENT '天气状况文字',
    wind_direction VARCHAR(32) NULL COMMENT '风向',
    wind_scale VARCHAR(16) NULL COMMENT '风力等级',
    wind_speed INT NULL COMMENT '风速（公里/小时）',
    humidity INT NULL COMMENT '相对湿度（百分比）',
    precipitation DECIMAL(8,2) NULL COMMENT '过去1小时降水量（毫米）',
    pressure INT NULL COMMENT '大气压强（百帕）',
    visibility DECIMAL(5,1) NULL COMMENT '能见度（公里）',
    cloud INT NULL COMMENT '云量（百分比）',
    dew INT NULL COMMENT '露点温度',
    aqi INT NULL COMMENT '空气质量指数',
    aqi_level VARCHAR(16) NULL COMMENT '空气质量等级',
    aqi_category VARCHAR(16) NULL COMMENT '空气质量类别（优/良/轻度污染等）',
    primary_pollutant VARCHAR(32) NULL COMMENT '首要污染物',
    pm25 DECIMAL(6,2) NULL COMMENT 'PM2.5浓度（μg/m³）',
    pm10 DECIMAL(6,2) NULL COMMENT 'PM10浓度（μg/m³）',
    no2 DECIMAL(6,2) NULL COMMENT 'NO2浓度（μg/m³）',
    o3 DECIMAL(6,2) NULL COMMENT 'O3浓度（μg/m³）',
    so2 DECIMAL(6,2) NULL COMMENT 'SO2浓度（μg/m³）',
    co DECIMAL(4,2) NULL COMMENT 'CO浓度（mg/m³）',
    solar_term VARCHAR(32) NULL COMMENT '当前节气',
    solar_term_desc VARCHAR(500) NULL COMMENT '节气描述',
    solar_term_proverb VARCHAR(255) NULL COMMENT '节气谚语',
    solar_term_custom VARCHAR(255) NULL COMMENT '节气习俗',
    next_solar_term VARCHAR(32) NULL COMMENT '下一节气',
    days_until_next_term INT NULL COMMENT '距离下一节气天数',
    source VARCHAR(32) NOT NULL DEFAULT 'qweather' COMMENT '数据来源：qweather和风天气，manual手动录入',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '软删除标记：0未删除，1已删除',
    PRIMARY KEY (id),
    INDEX idx_agri_climate_daily_user_id (user_id),
    INDEX idx_agri_climate_daily_farm_id (farm_id),
    INDEX idx_agri_climate_daily_record_date (record_date),
    INDEX idx_agri_climate_daily_location_date_deleted (location_id, record_date, deleted),
    INDEX idx_agri_climate_daily_farm_date_deleted (farm_id, record_date, deleted),
    CONSTRAINT fk_agri_climate_daily_user_id FOREIGN KEY (user_id) REFERENCES agri_user(id) ON DELETE RESTRICT,
    CONSTRAINT fk_agri_climate_daily_farm_id FOREIGN KEY (farm_id) REFERENCES agri_farm(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='每日天气数据表';

CREATE TABLE agri_weather_forecast (
    id VARCHAR(64) NOT NULL COMMENT '主键ID',
    climate_id VARCHAR(64) NOT NULL COMMENT '关联天气数据ID',
    user_id VARCHAR(64) NOT NULL COMMENT '所属用户ID',
    forecast_date DATE NOT NULL COMMENT '预报日期',
    sunrise TIME NULL COMMENT '日出时间',
    sunset TIME NULL COMMENT '日落时间',
    moonrise TIME NULL COMMENT '月升时间',
    moonset TIME NULL COMMENT '月落时间',
    moon_phase VARCHAR(64) NULL COMMENT '月相名称',
    moon_phase_icon VARCHAR(16) NULL COMMENT '月相图标代码',
    temp_max INT NULL COMMENT '最高温度',
    temp_min INT NULL COMMENT '最低温度',
    icon_day VARCHAR(16) NULL COMMENT '白天天气图标代码',
    text_day VARCHAR(64) NULL COMMENT '白天天气状况文字',
    icon_night VARCHAR(16) NULL COMMENT '夜间天气图标代码',
    text_night VARCHAR(64) NULL COMMENT '夜间天气状况文字',
    wind_dir_day VARCHAR(32) NULL COMMENT '白天风向',
    wind_scale_day VARCHAR(16) NULL COMMENT '白天风力等级',
    wind_speed_day INT NULL COMMENT '白天风速（公里/小时）',
    wind_dir_night VARCHAR(32) NULL COMMENT '夜间风向',
    wind_scale_night VARCHAR(16) NULL COMMENT '夜间风力等级',
    wind_speed_night INT NULL COMMENT '夜间风速（公里/小时）',
    humidity INT NULL COMMENT '相对湿度（百分比）',
    precipitation DECIMAL(8,2) NULL COMMENT '预报当天总降水量（毫米）',
    pressure INT NULL COMMENT '大气压强（百帕）',
    visibility DECIMAL(5,1) NULL COMMENT '能见度（公里）',
    cloud INT NULL COMMENT '云量（百分比）',
    uv_index INT NULL COMMENT '紫外线强度指数',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '软删除标记：0未删除，1已删除',
    PRIMARY KEY (id),
    INDEX idx_agri_weather_forecast_climate_id (climate_id),
    INDEX idx_agri_weather_forecast_user_id (user_id),
    INDEX idx_agri_weather_forecast_date_deleted (forecast_date, deleted),
    INDEX idx_agri_weather_forecast_climate_date_deleted (climate_id, forecast_date, deleted),
    CONSTRAINT fk_agri_weather_forecast_climate_id FOREIGN KEY (climate_id) REFERENCES agri_climate_daily(id) ON DELETE CASCADE,
    CONSTRAINT fk_agri_weather_forecast_user_id FOREIGN KEY (user_id) REFERENCES agri_user(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='天气预报表';

CREATE TABLE agri_weather_alert (
    id VARCHAR(64) NOT NULL COMMENT '主键ID',
    user_id VARCHAR(64) NOT NULL COMMENT '所属用户ID',
    farm_id VARCHAR(64) NULL COMMENT '关联农场ID',
    alert_source_id VARCHAR(64) NULL COMMENT '预警源ID（和风天气返回）',
    sender_name VARCHAR(100) NULL COMMENT '预警发布机构名称',
    event_type_name VARCHAR(64) NULL COMMENT '预警事件类型名称（如暴雨、大风）',
    event_type_code VARCHAR(16) NULL COMMENT '预警事件类型代码',
    severity VARCHAR(16) NULL COMMENT '预警严重程度：minor轻微，moderate中等，severe严重，extreme极端',
    severity_color VARCHAR(16) NULL COMMENT '预警颜色代码：blue蓝色，yellow黄色，orange橙色，red红色',
    headline VARCHAR(255) NULL COMMENT '预警简要描述',
    description TEXT NULL COMMENT '预警详细描述',
    instruction TEXT NULL COMMENT '防御指南',
    issued_time DATETIME NULL COMMENT '发布时间',
    effective_time DATETIME NULL COMMENT '生效时间',
    onset_time DATETIME NULL COMMENT '开始时间',
    expire_time DATETIME NULL COMMENT '失效时间',
    status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态：active有效，expired已过期，cancelled已取消',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '软删除标记：0未删除，1已删除',
    PRIMARY KEY (id),
    INDEX idx_agri_weather_alert_user_id (user_id),
    INDEX idx_agri_weather_alert_farm_id (farm_id),
    INDEX idx_agri_weather_alert_severity_status_deleted (severity, status, deleted),
    INDEX idx_agri_weather_alert_expire_time_deleted (expire_time, deleted),
    CONSTRAINT fk_agri_weather_alert_user_id FOREIGN KEY (user_id) REFERENCES agri_user(id) ON DELETE RESTRICT,
    CONSTRAINT fk_agri_weather_alert_farm_id FOREIGN KEY (farm_id) REFERENCES agri_farm(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='天气预警表';